---
# tasks file for webserver
- name: Install Apache2 Packages
  apt: name=apache2 state=present

- name: Start Apache Service
  service: name=apache2 state=started

- name: Deploy Custom Index Page
  copy: src=files/sample.html dest={{doc_root}}/index.html

- name: Deploy Custom Info Page
  template: src=templates/info.j2 dest={{doc_root}}/info.html
