---


- hosts: web
  become: yes
  vars:
    doc_root: "/var/www/html"
    username: "Amit Vashist" 
  tasks: 
  - name: Install Apache2 Packages 
    apt: name=apache2 state=present 

  - name: Start Apache Service 
    service: name=apache2 state=started 

  - name: Deploy Custom Index Page
    copy: src=files/sample.html dest={{doc_root}}/index.html
  
  - name: Deploy Custom Info Page
    template: src=templates/info.j2 dest={{doc_root}}/info.html


- hosts: web 
  become: yes 
  tasks: 
  - name: Install NTP Packages 
    apt: name=ntp state=present
