---


- hosts: web
  become: yes 
  tasks: 
  - name: Install Apache2 Packages 
    apt: name=apache2 state=present 

  - name: Start Apache Service 
    service: name=apache2 state=started 

  - name: Deploy Custom Index Page
    copy: src=files/sample.html dest=/var/www/html/index.html
  

- hosts: web 
  become: yes 
  tasks: 
  - name: Install NTP Packages 
    apt: name=ntp state=present
